---
- name: Create systemd service unit
  template:
    src: health-check.service.j2
    dest: /etc/systemd/system/health-check.service
    owner: root
    group: root
    mode: '0644'
  notify: systemd daemon reload

- name: Create systemd timer unit
  template:
    src: health-check.timer.j2
    dest: /etc/systemd/system/health-check.timer
    owner: root
    group: root
    mode: '0644'
  notify: systemd daemon reload

- name: Enable and start health-check timer
  systemd:
    name: health-check.timer
    enabled: yes
    state: started
    daemon_reload: yes
